apiVersion : apps/v1
kind: Deployment
metadata:
  name: devachandockerspringboot 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devachandockerspringboot
  template:
    metadata:
      labels:
        app: devachandockerspringboot 
    spec:
      containers:
        - name: devachandockerspringboot 
          image: myacrrepo53111.azurecr.io/devachandockerspringboot
          ports:
          - containerPort: 80